select u.txt_login_id as txtLoginId,
      u.txt_user_signature as txtUserSignature,
      ifnull(u.flg_force_passwd_chg, 'N') as FlgForcePasswdChg,
      ifnull(u.dat_last_passwd_chg, g.dat_system_asof) as DatLastPasswdChg,
      if(datediff(g.dat_system_asof, u.dat_last_passwd_chg) >= g.num_days_passwd_expire, 'Y', 'N') as FlgPasswdExpired,
      ifnull(u.txt_user_fname, '') as TxtUserFname,
      ifnull(u.txt_user_mname, '') as TxtUserMname,
      ifnull(u.txt_user_lname, '') as TxtUserLname,
      ifnull(u.txt_employee_id, '') as TxtEmployeeId,
      ifnull(u.cod_language, g.cod_language) as CodLanguage,
      ifnull(u.txt_user_email_id, '') as TxtUserEmailId,
      ifnull(u.txt_user_mobile_phone, '') as TxtUserMobilePhone,
      ifnull(u.txt_device_assigned, '') as TxtDeviceAssigned,
      ifnull(u.cod_user_designation, '') as CodUserDesignation,
      ifnull(u.txt_credit_approver_id, '') as TxtCreditApproverId,
      ifnull(u.txt_manager_login_id, '') as TxtManagerLoginId,
      ifnull(u.txt_default_reviewer_id, '') as TxtDefaultReviewerId,
      ifnull(u.cod_home_branch, '') as CodHomeBranch,
      ufIsHoliday(u.cod_home_branch) as NumIsHoliday,
      ifnull(u.id_parent_company_3rdparty, 0) as IdParentCompany3rdparty,
      ifnull(u.flg_disabled, 'N') as FlgDisabled,
      ifnull(u.flg_user_logged_in, 'N') as FlgUserLoggedIn,
      ifnull(u.flg_functional_id, 'N') as FlgFunctionalId,
      ifnull(u.num_failed_pwd, 0) as NumFailedPwd,
      if(ifnull(u.num_failed_pwd, 0) > :numFailedPwd, 'Y', 'N') as NumFailedPwdLimitExceeded,
      if(u.dat_profile_expiry < g.dat_system_asof, 'Y', 'N') as FlgProfileExpired,
      ifnull(u.num_time_start_wkday, 800) as NumTimeStartWkday,
      ifnull(u.num_time_end_wkday, 2000) as NumTimeEndWkday,
      ifnull(u.num_time_start_wkend, 900) as NumTimeStartWkend,
      ifnull(u.num_time_end_wkend, 1400) as NumTimeEndWkend,
      ifnull(u.num_time_start_holiday, 900) as NumTimeStartHoliday,
      ifnull(u.num_time_end_holiday, 1400) as NumTimeEndHoliday,
      u.cod_2fa_question_1 as Cod2faQuestion1,
      u.txt_2fa_answer_1 as Txt2faAnswer1,
      u.cod_2fa_question_2 as Cod2faQuestion2,
      u.txt_2fa_answer_2 as Txt2faAnswer2,
      u.cod_2fa_question_3 as Cod2faQuestion3,
      u.txt_2fa_answer_3 as Txt2faAnswer3,
      u.cod_2fa_question_4 as Cod2faQuestion4,
      u.txt_2fa_answer_4 as Txt2faAnswer4,
      u.cod_2fa_question_5 as Cod2faQuestion5,
      u.txt_2fa_answer_5 as Txt2faAnswer5,
      ifnull(u.cod_home_module, 'LOS') as CodHomeModule,
      u.cod_home_menu as CodHomeMenu,
      ifnull(u.enu_user_gender, 'N/A') as EnuUserGender,
      ifnull(u.dat_user_birth, '1900-01-01') as DatUserBirth,
      ifnull(u.txt_parent_company_name, '') as TxtParentCompanyName,
      ifnull(u.flg_parent_company_verified, 'N') as FlgParentCompanyVerified,
      u.dat_time_parent_company_verified as DatTimeParentCompanyVerified,
      ifnull(u.cod_department, '') as CodDepartment,
      ifnull(u.dat_last_login, g.dat_system_asof) as DatLastLogin,
      ifnull(u.dat_profile_expiry, g.dat_next_monthend) as DatProfileExpiry
from  sec_user_master u, sys_global_vars g
where u.cod_rec_status = 'A'
and   g.cod_rec_status = 'A'
and   txt_login_id=:userId
and   txt_user_signature=:userSignature;